### ISSUE TITLE
Feature Request: Join Jitsi Meet Meetings to create Live Transcriptions

### ISSUE THREAD

**Issue by candideu** [Meeting-Baas/transcript-seeker#3]

**Comment by Lazare-42** [comment]
thanks for your request :)

Unfortunately this would have to be handled by [MeetingBaas' API](https://meetingbaas.com) directly and right now there's no strong business case to do that. 

However, we are thinking of adding screen recording with Swift on MacOS to transcript-seeker, this could solve your problem.
